import { ProductInterface } from '../types/data';
import contentImage from '../assets/image.jpg';
import mainPhoto from "../assets/main photo.jpg";
import miniPhoto from "../assets/mini photo.jpg";
import photoInBasket from "../assets/imageSmall.png"


export const productsData: ProductInterface[] = [
    {
        title: "Essence Mascara Lash Princess",
        id: "1",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month",
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "2",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month",
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "3",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month"
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "4",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month"
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "5",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month"
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "6",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month",
        countInBasket: 1
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "7",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month"
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "8",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month"
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "9",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month"
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "10",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month"
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "11",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month"
    },
    {
        title: "Essence Mascara Lash Princess",
        id: "12",
        image: contentImage,
        ProductBigImage: mainPhoto,
        ProductMiniImage: miniPhoto, 
        ProductInBasketImage: photoInBasket,
        discount: "14.5%",
        price: "110 $",
        priceInProduct: "7.17$",
        oldprice: "9.99$",
        category: "electronics, selfie accessories",
        description: "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
        rating: 4,
        amount: "In Stock - Only 5 left!",
        warrantly: "1 month warranty",
        ships: "Ships in 1 month"
    }
]
